//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//
//     このファイルへの変更は、正しくない動作の原因となる場合があります。
//     また、コードの再生成時には変更が失われます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttpAuthModule.SampleWeb
{


    public partial class Default
    {

        /// <summary>
        /// form1 コントロール。
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド。
        /// 変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
